services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - aspire-network

  adminer:
    image: dpage/pgadmin4:9.7.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 8080:80
    networks:
      - aspire-network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  aspire-network:
    driver: bridge
