services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - aspire-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - aspire-network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  aspire-network:
    driver: bridge
