// <auto-generated />
using System;
using Aspire.MinimalApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AspireApp.MinimalApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251103135843_InitialCreateV1")]
    partial class InitialCreateV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.1.25451.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspireApp.SharedLib.Models.HurricaneAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ExpectedLandfall")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double>("WindSpeedMph")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.HasIndex("Severity");

                    b.ToTable("HurricaneAlerts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 4,
                            CreatedAt = new DateTime(2024, 10, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Major hurricane with extremely dangerous winds. Prepare for life-threatening storm surge and destructive winds.",
                            ExpectedLandfall = new DateTime(2024, 10, 15, 6, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Location = "Gulf of Mexico, approaching Florida West Coast",
                            Name = "Hurricane Milton",
                            Severity = 4,
                            UpdatedAt = new DateTime(2024, 10, 14, 12, 0, 0, 0, DateTimeKind.Utc),
                            WindSpeedMph = 150.0
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            CreatedAt = new DateTime(2024, 10, 13, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tropical storm conditions expected. Monitor for potential strengthening.",
                            IsActive = true,
                            Location = "Atlantic Ocean, moving northwest",
                            Name = "Tropical Storm Nadine",
                            Severity = 2,
                            UpdatedAt = new DateTime(2024, 10, 14, 8, 0, 0, 0, DateTimeKind.Utc),
                            WindSpeedMph = 85.0
                        });
                });

            modelBuilder.Entity("AspireApp.SharedLib.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A sample product for testing",
                            Name = "Sample Product 1",
                            Price = 29.99m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Another sample product",
                            Name = "Sample Product 2",
                            Price = 49.99m,
                            Stock = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
